import java.util.Map;

public class TestData {
    public static final Map<Integer, String> TAGS = Map.ofEntries(
            Map.entry(56, "Sort"),
            Map.entry(148, "Sort"),
            Map.entry(27, "Sort"),
            Map.entry(179, "Sort"),
            Map.entry(75, "Sort"),
            Map.entry(215, "Sort"),
            Map.entry(4, "Sort"),
            Map.entry(206, "LinkedList"),
            Map.entry(876, "LinkedList"),
            Map.entry(160, "LinkedList"),
            Map.entry(141, "LinkedList"),
            Map.entry(92, "LinkedList"),
            Map.entry(328, "LinkedList"),
            Map.entry(225, "Queue"),
            Map.entry(346, "Queue"),
            Map.entry(281, "Queue"),
            Map.entry(1429, "Queue"),
            Map.entry(54, "Queue"),
            Map.entry(362, "Queue"),
            Map.entry(155, "Stack"),
            Map.entry(232, "Stack"),
            Map.entry(150, "Stack"),
            Map.entry(224, "Stack"),
            Map.entry(20, "Stack"),
            Map.entry(1472, "Stack"),
            Map.entry(1209, "Stack"),
            Map.entry(1249, "Stack"),
            Map.entry(735, "Stack"),
            Map.entry(1, "Hash"),
            Map.entry(146, "Hash"),
            Map.entry(128, "Hash"),
            Map.entry(73, "Hash"),
            Map.entry(380, "Hash"),
            Map.entry(49, "Hash"),
            Map.entry(350, "Hash"),
            Map.entry(299, "Hash"),
            Map.entry(348, "Hash"),
            Map.entry(973, "Heap"),
            Map.entry(347, "Heap"),
            Map.entry(23, "Heap"),
            Map.entry(264, "Heap"),
            Map.entry(1086, "Heap"),
            Map.entry(88, "Heap"),
            Map.entry(692, "Heap"),
            Map.entry(378, "Heap"),
            Map.entry(295, "Heap"),
            Map.entry(767, "Heap"),
            Map.entry(1438, "Heap")
    );
}
